/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package project_group;

/**
 *
 * @author Jamson
 */
import javax.swing.*;
public class Log_In_Sign_Up extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Log_In_Sign_Up.class.getName());

    /**
     * Creates new form Log_In_Sign_Up
     */
   
    public Log_In_Sign_Up() {
        initComponents();
        
            // ---- CENTERING CONTAINER1 ----
    JPanel centerPanel = new JPanel(new java.awt.GridBagLayout());
    centerPanel.add(Container1, new java.awt.GridBagConstraints());

    // Clear the JFrame first, then add the new centered layout
    getContentPane().removeAll();
    getContentPane().setLayout(new java.awt.BorderLayout());
    getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

    pack(); // Resize the frame to fit preferred sizes
    setLocationRelativeTo(null); // Center the entire JFrame on screen
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Container1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Company_Name = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Tagline = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Lbl_Lg_In = new javax.swing.JLabel();
        Lbl_Email = new javax.swing.JLabel();
        Field_Email = new javax.swing.JTextField();
        Lbl_Passwd = new javax.swing.JLabel();
        Feild_Passwd = new javax.swing.JPasswordField();
        Btn_Lg_In = new javax.swing.JButton();
        Lbl_No_Accnt = new javax.swing.JLabel();
        Btn_Sign_Up_Lg_In = new javax.swing.JButton();

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\Java group project\\LogoImage4.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(800, 500));

        Container1.setBackground(new java.awt.Color(255, 255, 255));
        Container1.setPreferredSize(new java.awt.Dimension(800, 500));
        Container1.setLayout(null);

        Left.setBackground(new java.awt.Color(0, 102, 255));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        Company_Name.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        Company_Name.setForeground(new java.awt.Color(0, 0, 0));
        Company_Name.setText("LUSCIOUS");

        Logo.setIcon(new javax.swing.ImageIcon("D:\\Documents\\Java group project\\LogoImage6.png")); // NOI18N

        Tagline.setText("*Shaping Tomorrow Elegantly");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(Logo))
                    .addGroup(LeftLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tagline, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Company_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Company_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tagline, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        Container1.add(Left);
        Left.setBounds(0, 0, 390, 500);

        Right.setMinimumSize(new java.awt.Dimension(400, 500));
        Right.setOpaque(false);
        Right.setPreferredSize(new java.awt.Dimension(400, 500));

        Lbl_Lg_In.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        Lbl_Lg_In.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Lg_In.setText("LOGIN");

        Lbl_Email.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Lbl_Email.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Email.setText("Email");

        Field_Email.setBackground(new java.awt.Color(255, 255, 255));
        Field_Email.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Field_Email.setForeground(new java.awt.Color(0, 0, 0));
        Field_Email.setText("jTextField1");
        Field_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field_EmailActionPerformed(evt);
            }
        });

        Lbl_Passwd.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Lbl_Passwd.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Passwd.setText("Password");

        Feild_Passwd.setBackground(new java.awt.Color(255, 255, 255));
        Feild_Passwd.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Feild_Passwd.setForeground(new java.awt.Color(0, 0, 0));
        Feild_Passwd.setText("jPasswordField1");

        Btn_Lg_In.setBackground(new java.awt.Color(0, 102, 204));
        Btn_Lg_In.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Btn_Lg_In.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Lg_In.setText("Log In");
        Btn_Lg_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Lg_InActionPerformed(evt);
            }
        });

        Lbl_No_Accnt.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_No_Accnt.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Lbl_No_Accnt.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_No_Accnt.setText("You don't have an account?");

        Btn_Sign_Up_Lg_In.setBackground(new java.awt.Color(0, 102, 255));
        Btn_Sign_Up_Lg_In.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Btn_Sign_Up_Lg_In.setForeground(new java.awt.Color(0, 0, 0));
        Btn_Sign_Up_Lg_In.setText("Sign Up");
        Btn_Sign_Up_Lg_In.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Sign_Up_Lg_InActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_Passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Field_Email)
                                .addComponent(Feild_Passwd, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                            .addComponent(Btn_Lg_In)
                            .addGroup(RightLayout.createSequentialGroup()
                                .addComponent(Lbl_No_Accnt, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Sign_Up_Lg_In))))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(Lbl_Lg_In, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Lbl_Lg_In, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Lbl_Email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Field_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Lbl_Passwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Feild_Passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Btn_Lg_In)
                .addGap(22, 22, 22)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_No_Accnt)
                    .addComponent(Btn_Sign_Up_Lg_In))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        Container1.add(Right);
        Right.setBounds(390, 0, 410, 500);

        getContentPane().add(Container1, java.awt.BorderLayout.CENTER);
        Container1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Field_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field_EmailActionPerformed

    private void Btn_Lg_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Lg_InActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Lg_InActionPerformed

    private void Btn_Sign_Up_Lg_InActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Sign_Up_Lg_InActionPerformed
        Sign_Up SignupFrame = new Sign_Up();
        SignupFrame.setVisible(true);
        SignupFrame.pack();
        SignupFrame.setLocationRelativeTo(null); //center
    }//GEN-LAST:event_Btn_Sign_Up_Lg_InActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new Log_In_Sign_Up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Lg_In;
    private javax.swing.JButton Btn_Sign_Up_Lg_In;
    private javax.swing.JLabel Company_Name;
    private javax.swing.JPanel Container1;
    private javax.swing.JPasswordField Feild_Passwd;
    private javax.swing.JTextField Field_Email;
    private javax.swing.JLabel Lbl_Email;
    private javax.swing.JLabel Lbl_Lg_In;
    private javax.swing.JLabel Lbl_No_Accnt;
    private javax.swing.JLabel Lbl_Passwd;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel Tagline;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
