/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_group;

import javax.swing.JPanel;

/**
 *
 * @author Jamson
 */
public class Sign_Up extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sign_Up.class.getName());

    /**
     * Creates new form Sign_Up
     */
    public Sign_Up() {
        initComponents();
                            // ---- CENTERING CONTAINER1 ----
            JPanel centerPanel = new JPanel(new java.awt.GridBagLayout());
            centerPanel.add(Main_Sign_Up, new java.awt.GridBagConstraints());

            // Clear the JFrame first, then add the new centered layout
            getContentPane().removeAll();
            getContentPane().setLayout(new java.awt.BorderLayout());
            getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

            pack(); // Resize the frame to fit preferred sizes
            setLocationRelativeTo(null); // Center the entire JFrame on screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        Main_Sign_Up = new javax.swing.JPanel();
        Sign_Up_Lbl = new javax.swing.JLabel();
        Email_Sin_Up_Lbl = new javax.swing.JLabel();
        Email_Field_Sin_up = new javax.swing.JTextField();
        Passwd_Lbl_Sin_Up = new javax.swing.JLabel();
        Field_Passwd_Sin_up = new javax.swing.JPasswordField();
        Confm_Passwd_fld_Sin_Up = new javax.swing.JLabel();
        Fld_Cnfm_passwd_Sin_Up = new javax.swing.JPasswordField();
        Sign_Up_Btn = new javax.swing.JButton();

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Main_Sign_Up.setBackground(new java.awt.Color(0, 102, 255));
        Main_Sign_Up.setPreferredSize(new java.awt.Dimension(400, 500));

        Sign_Up_Lbl.setBackground(new java.awt.Color(255, 255, 255));
        Sign_Up_Lbl.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        Sign_Up_Lbl.setForeground(new java.awt.Color(0, 0, 0));
        Sign_Up_Lbl.setText("SIGN UP");

        Email_Sin_Up_Lbl.setBackground(new java.awt.Color(255, 255, 255));
        Email_Sin_Up_Lbl.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Email_Sin_Up_Lbl.setForeground(new java.awt.Color(0, 0, 0));
        Email_Sin_Up_Lbl.setText("Email");

        Email_Field_Sin_up.setBackground(new java.awt.Color(255, 255, 255));
        Email_Field_Sin_up.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Email_Field_Sin_up.setForeground(new java.awt.Color(0, 0, 0));
        Email_Field_Sin_up.setText("jTextField1");
        Email_Field_Sin_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Email_Field_Sin_upActionPerformed(evt);
            }
        });

        Passwd_Lbl_Sin_Up.setBackground(new java.awt.Color(255, 255, 255));
        Passwd_Lbl_Sin_Up.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Passwd_Lbl_Sin_Up.setForeground(new java.awt.Color(0, 0, 0));
        Passwd_Lbl_Sin_Up.setText("Enter Password");

        Field_Passwd_Sin_up.setBackground(new java.awt.Color(255, 255, 255));
        Field_Passwd_Sin_up.setForeground(new java.awt.Color(0, 0, 0));
        Field_Passwd_Sin_up.setText("jPasswordField1");

        Confm_Passwd_fld_Sin_Up.setBackground(new java.awt.Color(255, 255, 255));
        Confm_Passwd_fld_Sin_Up.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Confm_Passwd_fld_Sin_Up.setForeground(new java.awt.Color(0, 0, 0));
        Confm_Passwd_fld_Sin_Up.setText("Confirm Password");

        Fld_Cnfm_passwd_Sin_Up.setBackground(new java.awt.Color(255, 255, 255));
        Fld_Cnfm_passwd_Sin_Up.setForeground(new java.awt.Color(0, 0, 0));
        Fld_Cnfm_passwd_Sin_Up.setText("jPasswordField2");

        Sign_Up_Btn.setBackground(new java.awt.Color(102, 153, 255));
        Sign_Up_Btn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Sign_Up_Btn.setForeground(new java.awt.Color(0, 0, 0));
        Sign_Up_Btn.setText("Sign Up");
        Sign_Up_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sign_Up_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Main_Sign_UpLayout = new javax.swing.GroupLayout(Main_Sign_Up);
        Main_Sign_Up.setLayout(Main_Sign_UpLayout);
        Main_Sign_UpLayout.setHorizontalGroup(
            Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Sign_UpLayout.createSequentialGroup()
                .addGroup(Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Main_Sign_UpLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Email_Sin_Up_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Email_Field_Sin_up)
                            .addComponent(Passwd_Lbl_Sin_Up)
                            .addComponent(Field_Passwd_Sin_up, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(Confm_Passwd_fld_Sin_Up, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fld_Cnfm_passwd_Sin_Up)))
                    .addGroup(Main_Sign_UpLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(Sign_Up_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Main_Sign_UpLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Sign_Up_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        Main_Sign_UpLayout.setVerticalGroup(
            Main_Sign_UpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_Sign_UpLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(Sign_Up_Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Email_Sin_Up_Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_Field_Sin_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Passwd_Lbl_Sin_Up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field_Passwd_Sin_up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Confm_Passwd_fld_Sin_Up)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fld_Cnfm_passwd_Sin_Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Sign_Up_Btn)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main_Sign_Up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 549, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main_Sign_Up, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Email_Field_Sin_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Email_Field_Sin_upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Email_Field_Sin_upActionPerformed

    private void Sign_Up_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sign_Up_BtnActionPerformed
        
        
    }//GEN-LAST:event_Sign_Up_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(() -> new Sign_Up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confm_Passwd_fld_Sin_Up;
    private javax.swing.JTextField Email_Field_Sin_up;
    private javax.swing.JLabel Email_Sin_Up_Lbl;
    private javax.swing.JPasswordField Field_Passwd_Sin_up;
    private javax.swing.JPasswordField Fld_Cnfm_passwd_Sin_Up;
    private javax.swing.JPanel Main_Sign_Up;
    private javax.swing.JLabel Passwd_Lbl_Sin_Up;
    private javax.swing.JButton Sign_Up_Btn;
    private javax.swing.JLabel Sign_Up_Lbl;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
